In [2]:
import scipy as sp
from scipy import integrate
from scipy import special
from scipy import interpolate
import numpy as np
import time

In [3]:
def super_integrate(func, a, b):
    return sp.integrate.fixed_quad(func=func, a=a, b=b, n=1e3)[0]

def gamma_def(x):
    inner_gamma = lambda t,y: np.log(1/t)**(y-1)
    return sp.integrate.quad(func=lambda t: inner_gamma(t,x), a=0, b=1)[0]

def gamma_repre(x):    
    gammas = np.vectorize(gamma_def)(x)
    return gammas

In [4]:
def phi1(y, n=1):
    result = super_integrate(gamma_repre, n, y)
    return result

In [5]:
phi1(np.sqrt(2))

0.3832333065211719

In [6]:
def Chebyshev_points(xmin,xmax,n):
    ns = np.arange(1,n+1)
    x = np.cos((2*ns-1)*np.pi/(2*n))
    #y = np.sin((2*ns-1)*np.pi/(2*n))
    return (xmin+xmax)/2 + (xmax-xmin)*x/2

In [7]:
Chebyshev_points(1, 10, 5)

array([9.77975432, 8.14503364, 5.5       , 2.85496636, 1.22024568])

In [8]:
def gamma_interpolator_var(y, n):
    xi = Chebyshev_points(1, y, n)
    yi = gamma_repre(xi)
    interpolator = interpolate.BarycentricInterpolator(xi,yi)
    return interpolator

In [9]:
nums = np.array([1,2,3,4,5])
polinomio_interpolador = gamma_interpolator_var(5, 100)
print(polinomio_interpolador(nums))

[ 1.  1.  2.  6. 24.]


In [10]:
def gamma_interpolator_fixed(n):
    xi = Chebyshev_points(1, 10, n)
    yi = gamma_repre(xi)
    interpolator = interpolate.BarycentricInterpolator(xi,yi)
    return interpolator

In [11]:
nums = np.array([1,2,3,4,5,6,7,8])
polinomio_interpolador = gamma_interpolator_fixed(100)
print(polinomio_interpolador(nums))

[9.99997948e-01 9.99999047e-01 2.00000189e+00 6.00000265e+00
 2.39999995e+01 1.19999999e+02 7.20000006e+02 5.04000001e+03]


In [12]:
result = np.array([9.99998011e-01, 9.99999078e-01, 2.00000182e+00, 6.00000254e+00, 2.39999995e+01, 1.19999999e+02, 7.20000005e+02, 5.04000001e+03])

In [13]:
def phi3(inter, y, n):
    result = super_integrate(inter, 1, y)
    return result

In [14]:
inter = gamma_interpolator_fixed(10000)

C:\Users\nicer\anaconda3\lib\site-packages\scipy\interpolate\polyint.py:545: RuntimeWarning: overflow encountered in reduce
  self.wi[j] = np.multiply.reduce(self.xi[:j]-self.xi[j])
C:\Users\nicer\anaconda3\lib\site-packages\scipy\interpolate\polyint.py:546: RuntimeWarning: divide by zero encountered in reciprocal
  self.wi **= -1


In [15]:
phi3(inter, 1, 8)

C:\Users\nicer\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


nan

In [18]:
l = np.linspace(2, 11, 5)

np.array([phi1(x) for x in l])

array([9.22745951e-01, 7.62014171e+00, 1.72874888e+02, 1.15916630e+04,
       1.57253537e+06])