In [3]:
import numpy as np
import IPython
import time
from scipy.io import wavfile
from scipy.signal import stft
from scipy.signal import istft

In [4]:
# Esta función de no debe ser modificada.
def WAV_to_Array(WAV_file):
    sample_rate, data = wavfile.read(WAV_file)
    if(len(data.shape) > 1): # En caso de que tenga más de un canal de audio, se trabaja con el primero
        data = data[:,0]
    
    return sample_rate, data

# Esta función de no debe ser modificada.
def play_audio(data, sample_rate):
    IPython.display.display(IPython.display.Audio(data, rate=sample_rate))
    return

# Esta función de no debe ser modificada.
def STFT(data):
    _, _, M = stft(data)
    return M
    
# Esta función de no debe ser modificada.
def ISTFT(M):
    _, data = istft(M)
    return data

In [5]:
sample_rate, data = WAV_to_Array("original.wav")
d = STFT(data=data)

## Tests

In [6]:
def Split(M):

    M_Re = list()
    M_Im = list()

    for i in range(len(M)):
        real = list()
        img = list()
        for j in range(len(M[i])):
            real.append(np.real(M[i][j]))
            img.append(np.imag(M[i][j]))
        M_Re.append(real)
        M_Im.append(img)
    
    M_Re = np.array(M_Re)
    M_Im = np.array(M_Im)

    return M_Re, M_Im

In [7]:
def Merge(M_Re, M_Im):
    M = M_Re + M_Im*1j

    return M

In [8]:
# def Split(M):
#     M_Re = np.real(M).astype(np.float64)
#     M_Im = np.imag(M).astype(np.float64)
#     return M_Re, M_Im

In [9]:
M_Re, M_Im = Split(d)
s = Merge(M_Re, M_Im)

In [10]:
comparison = d == s
equal_arrays = comparison.all()
print(equal_arrays)

True


In [40]:
def PCA_SVD(M, m):
    # Apply PCA
    mu = np.mean(M, axis=0)
    Z = M - mu

    u, s, vh = np.linalg.svd(Z, full_matrices=False)
    
    V = vh.T[:, :m]
    Y = Z.dot(V)

    return  V, Y, mu

In [41]:
V, Y, mu = PCA_SVD(M_Re, 3)
print(V)

[[ 4.4385198e-17  5.9151150e-17 -1.7692978e-17]
 [ 2.8311219e-16  1.4796842e-16  3.2039369e-17]
 [ 7.1310585e-17 -1.0629443e-17  2.5913291e-17]
 ...
 [ 5.2774008e-03  1.6917860e-03 -2.8191059e-04]
 [ 2.9871315e-03  7.7757137e-03  5.6850561e-03]
 [ 7.7815233e-03 -7.6680477e-03  7.5204768e-03]]


In [42]:
def PCA_M(V, Y, mu):
    Mm = Y.dot(V.T) + mu
    return Mm

In [44]:
Mn = PCA_M(V, Y, mu)
Mn

array([[-5.3946678e-12, -1.7530522e-11, -1.0460134e-12, ...,
        -2.6365994e+02, -5.2298492e+02,  3.7795334e+02],
       [ 1.0726782e-11,  3.9715009e-11,  4.1415534e-12, ...,
         6.2770166e+02,  1.0998384e+03, -3.6320752e+02],
       [-1.3561164e-11, -6.1544540e-11, -1.0284906e-11, ...,
        -1.0264838e+03, -1.3260836e+03, -4.0851996e+02],
       ...,
       [ 2.0983606e-14,  6.8239346e-14,  4.0898507e-15, ...,
         5.1765933e+00,  4.9463615e+00,  4.3307681e+00],
       [ 2.0996073e-14,  6.8181917e-14,  4.0515771e-15, ...,
         5.1754856e+00,  4.9458847e+00,  4.3224812e+00],
       [ 2.0987740e-14,  6.8251631e-14,  4.0902903e-15, ...,
         5.1767931e+00,  4.9466591e+00,  4.3304033e+00]], dtype=float32)